application: two-server
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /login.html
  static_files: static/login.html
  upload: static/login.html
  secure: always

- url: /register.html
  static_files: static/register.html
  upload: static/register.html
  secure: always

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /register
  script: register.app
  secure: always

- url: /verify
  script: verify.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
