from google.appengine.ext import ndb

class UserList(ndb.Model):
    """Models a user list."""
    Username = ndb.StringProperty(required = True)
    Password = ndb.StringProperty(required = True)
    # The key used to generate HMAC-SHA1
    SecretKey = ndb.StringProperty(required = True, indexed=False)
    # The message used to generate HMAC-SHA1. Generated by request.
    Counter = ndb.StringProperty()
